version: '3.1'
services:
  ita-api-organization:
    build:
      dockerfile: ./ita_root/ita_api_organization/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - LISTEN_PORT=8000
      - PYTHONPATH=/exastro/
      - DEFAULT_LANGUAGE=ja
      - DB_HOST=ita-mariadb
      - DB_PORT=3306
      - DB_DATADBASE=ITA_DB
      - DB_USER=ITA_USER
      - DB_PASSWORD=password
      - DB_ROOT_PASSWORD=password
      - STORAGEPATH=/storage/
      - PLATFORM_API_HOST=platform-api
      - PLATFORM_API_PORT=8000
  ita-api-admin:
    build:
      dockerfile: ./ita_root/ita_api_admin/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - LISTEN_PORT=8079
      - PYTHONPATH=/exastro/
      - DEFAULT_LANGUAGE=ja
      - DB_HOST=ita-mariadb
      - DB_PORT=3306
      - DB_DATADBASE=ITA_DB
      - DB_USER=ITA_USER
      - DB_PASSWORD=password
      - DB_ROOT_PASSWORD=password
      - STORAGEPATH=/storage/
      - GITLAB_HOST=10.197.18.183
      - GITLAB_PORT=40080
      - GITLAB_ROOT_TOKEN=mzsQj8VU_zcSoSZsSX__
  ita-web-server:
    build:
      dockerfile: ./ita_root/ita_web_server/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - LISTEN_PORT=80
    ports:
      - "0.0.0.0:80:80"
  ita-mariadb:
    build:
      dockerfile: ./ita_root/ita_mariadb/Dockerfile
      context: ../.
    volumes:
      - ../.volumes/ita-mariadb/data:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=ITA_DB
      - MARIADB_USER=ITA_USER
      - MARIADB_PASSWORD=password

  ita-by-ansible-execute:
    build:
      dockerfile: ./ita_root/ita_by_ansible_execute/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - EXECUTE_INTERVAL=10
      - PYTHONPATH=/exastro/
      - DEFAULT_LANGUAGE=en
      - DB_HOST=ita-mariadb
      - DB_PORT=3306
      - DB_DATADBASE=ITA_DB
      - DB_USER=ITA_USER
      - DB_PASSWORD=password
      - DB_ROOT_PASSWORD=password
      - STORAGEPATH=/storage/
      - HOST_STORAGEPATH=/home/almalinux/uekawa-tomonari/it-automation2-test/.volumes/storage/
      - CONTAINER_BASE=docker
      - LAST_UPDATE_USER_ID=3
  # ita-by-ansible-legacy-role-vars-listup:
  #   build:
  #     dockerfile: ./ita_root/ita_by_ansible_legacy_role_vars_listup/Dockerfile
  #     context: ../.
  #     args:
  #       - HTTP_PROXY=${HTTP_PROXY}
  #       - http_proxy=${HTTP_PROXY}
  #       - HTTPS_PROXY=${HTTPS_PROXY}
  #       - https_proxy=${HTTPS_PROXY}
  #   environment:
  #     - EXECUTE_INTERVAL=10
  #     - PYTHONPATH=/exastro/
  #     - DEFAULT_LANGUAGE=en
  #     - DB_HOST=ita-mariadb
  #     - DB_PORT=3306
  #     - DB_DATADBASE=ITA_DB
  #     - DB_USER=ITA_USER
  #     - DB_PASSWORD=password
  #     - DB_ROOT_PASSWORD=password
  #     - STORAGEPATH=/storage/
  #     - GITLAB_HOST=10.197.18.183
  #     - GITLAB_PORT=40080
  #     - GITLAB_ROOT_TOKEN=mzsQj8VU_zcSoSZsSX__
  # ita-by-ansible-towermaster-sync:
  #   build:
  #     dockerfile: ./ita_root/ita_by_ansible_towermaster_sync/Dockerfile
  #     context: ../.
  #     args:
  #       - HTTP_PROXY=${HTTP_PROXY}
  #       - http_proxy=${HTTP_PROXY}
  #       - HTTPS_PROXY=${HTTPS_PROXY}
  #       - https_proxy=${HTTPS_PROXY}
  #   environment:
  #     - EXECUTE_INTERVAL=10
  #     - PYTHONPATH=/exastro/
  #     - DEFAULT_LANGUAGE=en
  #     - DB_HOST=ita-mariadb
  #     - DB_PORT=3306
  #     - DB_DATADBASE=ITA_DB
  #     - DB_USER=ITA_USER
  #     - DB_PASSWORD=password
  #     - DB_ROOT_PASSWORD=password
  #     - STORAGEPATH=/storage/
  #     - GITLAB_HOST=10.197.18.183
  #     - GITLAB_PORT=40080
  #     - GITLAB_ROOT_TOKEN=mzsQj8VU_zcSoSZsSX__
  # ita-by-conductor-synchronize:
  #   build:
  #     dockerfile: ./ita_root/ita_by_conductor_synchronize/Dockerfile
  #     context: ../.
  #     args:
  #       - HTTP_PROXY=${HTTP_PROXY}
  #       - http_proxy=${HTTP_PROXY}
  #       - HTTPS_PROXY=${HTTPS_PROXY}
  #       - https_proxy=${HTTPS_PROXY}
  #   environment:
  #     - EXECUTE_INTERVAL=10
  #     - PYTHONPATH=/exastro/
  #     - DEFAULT_LANGUAGE=en
  #     - DB_HOST=ita-mariadb
  #     - DB_PORT=3306
  #     - DB_DATADBASE=ITA_DB
  #     - DB_USER=ITA_USER
  #     - DB_PASSWORD=password
  #     - DB_ROOT_PASSWORD=password
  #     - STORAGEPATH=/storage/
  #     - GITLAB_HOST=10.197.18.183
  #     - GITLAB_PORT=40080
  #     - GITLAB_ROOT_TOKEN=mzsQj8VU_zcSoSZsSX__
  # ita-by-menu-create:
  #   build:
  #     dockerfile: ./ita_root/ita_by_menu_create/Dockerfile
  #     context: ../.
  #     args:
  #       - HTTP_PROXY=${HTTP_PROXY}
  #       - http_proxy=${HTTP_PROXY}
  #       - HTTPS_PROXY=${HTTPS_PROXY}
  #       - https_proxy=${HTTPS_PROXY}
  #   environment:
  #     - EXECUTE_INTERVAL=10
  #     - PYTHONPATH=/exastro/
  #     - DEFAULT_LANGUAGE=en
  #     - DB_HOST=ita-mariadb
  #     - DB_PORT=3306
  #     - DB_DATADBASE=ITA_DB
  #     - DB_USER=ITA_USER
  #     - DB_PASSWORD=password
  #     - DB_ROOT_PASSWORD=password
  #     - STORAGEPATH=/storage/
  #     - GITLAB_HOST=10.197.18.183
  #     - GITLAB_PORT=40080
  #     - GITLAB_ROOT_TOKEN=mzsQj8VU_zcSoSZsSX__
